import React, { useState, useEffect } from 'react';
import { 
  Users, 
  Search, 
  Filter, 
  Download, 
  Shield, 
  CreditCard, 
  Phone, 
  Mail, 
  Calendar, 
  MapPin,
  ArrowUpDown,
  Eye,
  X,
  Package,
  Building2
} from 'lucide-react';
import treeManager from '../utils/TreeManager'; 

// Helper function to recursively calculate subtree stats for Indirect metrics
// Helper to calculate subtree stats recursively
const getSubtreeStats = (node, excludeDirect = false) => {
  if (!node) {
    return { 
      count: 0, 
      totalSales: 0, 
      totalIncome: 0 
    };
  }

  let stats = {
    count: 1,
    totalSales: node.totalSales || 0,
    totalIncome: (node.directIncome || 0) + (node.indirectIncome || 0)
  };

  if (node.left) {
    const leftStats = getSubtreeStats(node.left, excludeDirect);
    stats.count += leftStats.count;
    stats.totalSales += leftStats.totalSales;
    stats.totalIncome += leftStats.totalIncome;
  }

  if (node.right) {
    const rightStats = getSubtreeStats(node.right, excludeDirect);
    stats.count += rightStats.count;
    stats.totalSales += rightStats.totalSales;
    stats.totalIncome += rightStats.totalIncome;
  }

  return stats;
};

function AdminDashboard() {
  const [users, setUsers] = useState([]);
  const [filteredUsers, setFilteredUsers] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState('all'); // 'all', 'customer', 'brand_owner'
  const [selectedUser, setSelectedUser] = useState(null); // For the detail modal
  const [sortConfig, setSortConfig] = useState({ key: 'joinDate', direction: 'desc' });

  // Fetch data on mount
  useEffect(() => {
    refreshData();
  }, []);

  // Fetch data from treeManager (keep existing)
  const refreshData = () => {
    const allNodes = Array.from(treeManager.allNodes.values());
    const enrichedUsers = allNodes.map(user => calculateUserMetrics(user));
    setUsers(enrichedUsers);
    setFilteredUsers(enrichedUsers);
  };

  // Complex Metric Calculation Logic
  const calculateUserMetrics = (user) => {
    // --- Direct Stats ---
    const leftDirectChild = user.left;
    const rightDirectChild = user.right;
    
    const directStats = {
      leftCount: leftDirectChild ? 1 : 0,
      rightCount: rightDirectChild ? 1 : 0,
      totalCount: (leftDirectChild ? 1 : 0) + (rightDirectChild ? 1 : 0),
      
      leftPurchaseValue: leftDirectChild ? (leftDirectChild.totalSales || 0) : 0,
      rightPurchaseValue: rightDirectChild ? (rightDirectChild.totalSales || 0) : 0,
      totalPurchaseValue: (leftDirectChild ? leftDirectChild.totalSales : 0) + (rightDirectChild ? rightDirectChild.totalSales : 0),
      
      // Direct Income is what the children generate (usually goes to parent), 
      // but here we are listing stats FOR the user. 
      // Usually "Left Direct Child Income" means income generated BY that specific left child.
      leftIncome: leftDirectChild ? (leftDirectChild.directIncome + leftDirectChild.indirectIncome) : 0,
      rightIncome: rightDirectChild ? (rightDirectChild.directIncome + rightDirectChild.indirectIncome) : 0,
      totalIncome: (leftDirectChild ? (leftDirectChild.directIncome + leftDirectChild.indirectIncome) : 0) + 
                   (rightDirectChild ? (rightDirectChild.directIncome + rightDirectChild.indirectIncome) : 0),
    };

    // --- Indirect Stats (Subtree minus Direct) ---
    const leftSubtreeStats = getSubtreeStats(leftDirectChild, true); // true = exclude the direct child itself
    const rightSubtreeStats = getSubtreeStats(rightDirectChild, true);

    const indirectStats = {
      leftCount: leftSubtreeStats.count,
      rightCount: rightSubtreeStats.count,
      totalCount: leftSubtreeStats.count + rightSubtreeStats.count,

      leftPurchaseValue: leftSubtreeStats.totalSales,
      rightPurchaseValue: rightSubtreeStats.totalSales,
      totalPurchaseValue: leftSubtreeStats.totalSales + rightSubtreeStats.totalSales,

      leftIncome: leftSubtreeStats.totalIncome,
      rightIncome: rightSubtreeStats.totalIncome,
      totalIncome: leftSubtreeStats.totalIncome + rightSubtreeStats.totalIncome,
    };

    return {
      ...user, // Spread original node data
      ...directStats,
      ...indirectStats,
      // Flattened convenience fields
      totalDirectReferrals: user.directReferrals ? user.directReferrals.length : 0
    };
  };

  // Filtering and Sorting Logic
  useEffect(() => {
    let result = users;

    // Filter by Type
    if (filterType !== 'all') {
      result = result.filter(u => u.userType === filterType);
    }

    // Search Logic
    if (searchQuery) {
      const lowerQ = searchQuery.toLowerCase();
      result = result.filter(u => 
        u.name.toLowerCase().includes(lowerQ) ||
        u.id.toLowerCase().includes(lowerQ) ||
        (u.email && u.email.toLowerCase().includes(lowerQ)) ||
        (u.mobile && u.mobile.toString().includes(lowerQ))
      );
    }

    // Sorting
    result.sort((a, b) => {
      let valA = a[sortConfig.key];
      let valB = b[sortConfig.key];
      
      // Handle numeric strings
      if (typeof valA === 'string') valA = valA.toLowerCase();
      if (typeof valB === 'string') valB = valB.toLowerCase();

      if (valA < valB) return sortConfig.direction === 'asc' ? -1 : 1;
      if (valA > valB) return sortConfig.direction === 'asc' ? 1 : -1;
      return 0;
    });

    setFilteredUsers(result);
  }, [users, searchQuery, filterType, sortConfig]);

  const handleSort = (key) => {
    setSortConfig(prev => ({
      key,
      direction: prev.key === key && prev.direction === 'asc' ? 'desc' : 'asc'
    }));
  };

  // Summary Calculations
  const totalCustomers = users.filter(u => u.userType === 'customer').length;
  const totalBrandOwners = users.filter(u => u.userType === 'brand_owner').length;
  const kycVerifiedCount = users.filter(u => u.kycVerified).length;

  return (
    <div className="min-h-screen bg-gray-50 p-6 font-sans">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        body { font-family: 'Inter', sans-serif; }
      `}</style>

      {/* Header Section */}
      <div className="max-w-[1600px] mx-auto mb-8">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-800">Admin Dashboard</h1>
            <p className="text-gray-500">Manage Users & Inventory Data</p>
          </div>
          <button 
            onClick={refreshData}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm hover:bg-gray-50 text-gray-700 font-medium transition"
          >
            <ArrowUpDown size={18} />
            Refresh Data
          </button>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm font-medium text-gray-500">Total Users</p>
                <h3 className="text-2xl font-bold text-gray-800 mt-1">{users.length}</h3>
              </div>
              <div className="p-2 bg-blue-100 rounded-lg text-blue-600">
                <Users size={20} />
              </div>
            </div>
          </div>
          
          <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm font-medium text-gray-500">Customers</p>
                <h3 className="text-2xl font-bold text-blue-600 mt-1">{totalCustomers}</h3>
              </div>
              <div className="p-2 bg-blue-50 rounded-lg text-blue-500">
                <Users size={20} />
              </div>
            </div>
          </div>

          <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm font-medium text-gray-500">Brand Owners</p>
                <h3 className="text-2xl font-bold text-purple-600 mt-1">{totalBrandOwners}</h3>
              </div>
              <div className="p-2 bg-purple-50 rounded-lg text-purple-500">
                <Building2 size={20} />
              </div>
            </div>
          </div>

          <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm font-medium text-gray-500">KYC Verified</p>
                <h3 className="text-2xl font-bold text-green-600 mt-1">{kycVerifiedCount}</h3>
              </div>
              <div className="p-2 bg-green-50 rounded-lg text-green-500">
                <Shield size={20} />
              </div>
            </div>
          </div>
        </div>

        {/* Filters & Search Bar */}
        <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 mb-6 flex flex-col lg:flex-row gap-4 justify-between items-center">
          <div className="flex items-center gap-2 bg-gray-50 px-3 py-2 rounded-lg w-full lg:w-96">
            <Search size={18} className="text-gray-400" />
            <input 
              type="text" 
              placeholder="Search by Name, User ID, Email..." 
              className="bg-transparent border-none outline-none text-sm w-full text-gray-700"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <Filter size={18} className="text-gray-500" />
              <select 
                className="bg-gray-50 border border-gray-200 text-sm rounded-lg px-3 py-2 outline-none"
                value={filterType}
                onChange={(e) => setFilterType(e.target.value)}
              >
                <option value="all">All Users</option>
                <option value="customer">Customers</option>
                <option value="brand_owner">Brand Owners</option>
              </select>
            </div>
            
            <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition shadow-sm">
              <Download size={16} />
              Export CSV
            </button>
          </div>
        </div>

        {/* Data Table / Grid */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="bg-gray-50 text-gray-600 border-b border-gray-200">
                <tr>
                  <th 
                    className="p-4 font-semibold cursor-pointer hover:bg-gray-100"
                    onClick={() => handleSort('id')}
                  >
                    User ID
                  </th>
                  <th 
                    className="p-4 font-semibold cursor-pointer hover:bg-gray-100"
                    onClick={() => handleSort('name')}
                  >
                    Name
                  </th>
                  <th className="p-4 font-semibold">Type</th>
                  <th className="p-4 font-semibold">Contact</th>
                  <th className="p-4 font-semibold">KYC / Bank</th>
                  <th 
                    className="p-4 font-semibold cursor-pointer hover:bg-gray-100 text-right"
                    onClick={() => handleSort('totalIncome')}
                  >
                    Total Income (Dir + Ind)
                  </th>
                  <th className="p-4 font-semibold text-center">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {filteredUsers.length === 0 ? (
                  <tr>
                    <td colSpan="7" className="p-8 text-center text-gray-500">
                      No users found matching your criteria.
                    </td>
                  </tr>
                ) : (
                  filteredUsers.map((user) => (
                    <tr key={user.id} className="hover:bg-gray-50 transition group">
                      <td className="p-4 font-medium text-gray-900">{user.id}</td>
                      <td className="p-4">
                        <div className="font-medium text-gray-900">{user.name}</div>
                        <div className="text-xs text-gray-500">{user.email}</div>
                      </td>
                      <td className="p-4">
                        <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                          user.userType === 'customer' 
                            ? 'bg-blue-100 text-blue-800' 
                            : 'bg-purple-100 text-purple-800'
                        }`}>
                          {user.userType === 'brand_owner' ? 'Brand Owner' : 'Customer'}
                        </span>
                      </td>
                      <td className="p-4 text-gray-600">
                        <div className="flex items-center gap-1 text-xs mb-1">
                          <Phone size={12} className="text-gray-400"/> {user.mobile || 'N/A'}
                        </div>
                        <div className="flex items-center gap-1 text-xs">
                          <Mail size={12} className="text-gray-400"/> {user.email}
                        </div>
                      </td>
                      <td className="p-4">
                        <div className="flex flex-col gap-1">
                          <div className="flex items-center gap-1">
                            <span className={`text-xs font-medium ${user.kycVerified ? 'text-green-600' : 'text-red-500'}`}>
                              {user.kycVerified ? 'Verified' : 'Pending'}
                            </span>
                          </div>
                          <div className="flex items-center gap-1">
                            <span className={`text-xs font-medium ${user.bankAccount ? 'text-green-600' : 'text-red-500'}`}>
                              {user.bankAccount ? 'Added' : 'None'}
                            </span>
                          </div>
                        </div>
                      </td>
                      <td className="p-4 text-right font-semibold text-gray-700">
                        ₹{((user.totalIncome || 0) + (user.totalIncome || 0)).toLocaleString('en-IN', {maximumFractionDigits: 2})}
                      </td>
                      <td className="p-4 text-center">
                        <button 
                          onClick={() => setSelectedUser(user)}
                          className="p-2 bg-white border border-gray-200 rounded hover:bg-blue-50 hover:text-blue-600 hover:border-blue-200 transition text-gray-600"
                        >
                          <Eye size={16} />
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
          
          {/* Pagination Placeholder */}
          <div className="p-4 border-t border-gray-100 flex justify-between items-center text-xs text-gray-500">
            <span>Showing {filteredUsers.length} of {users.length} users</span>
            <div className="flex gap-2">
              <button className="px-3 py-1 border rounded hover:bg-gray-50">Previous</button>
              <button className="px-3 py-1 border rounded hover:bg-gray-50">Next</button>
            </div>
          </div>
        </div>
      </div>

      {/* Detail Modal */}
      {selectedUser && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-5xl max-h-[90vh] overflow-hidden flex flex-col">
            
            {/* Modal Header */}
            <div className="p-5 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
              <div>
                <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
                  {selectedUser.name} 
                  <span className={`text-xs px-2 py-0.5 rounded ${
                    selectedUser.userType === 'customer' 
                      ? 'bg-blue-100 text-blue-800' 
                      : 'bg-purple-100 text-purple-800'
                  }`}>
                    {selectedUser.userType === 'brand_owner' ? 'Brand Owner' : 'Customer'}
                  </span>
                </h2>
                <p className="text-sm text-gray-500">ID: {selectedUser.id} | Joined: {selectedUser.joinDate}</p>
              </div>
              <button 
                onClick={() => setSelectedUser(null)}
                className="p-2 hover:bg-gray-200 rounded-full transition text-gray-600"
              >
                <X size={20} />
              </button>
            </div>

            {/* Modal Body - Scrollable */}
            <div className="overflow-y-auto p-6 space-y-6">
              
              {/* Section 1: Personal Information */}
              <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div className="col-span-full mb-2 flex items-center gap-2 pb-2 border-b">
                  <Users className="text-blue-600" size={18} />
                  <h3 className="text-lg font-semibold text-gray-800">Personal Information</h3>
                </div>

                <DetailField label="Full Name" value={selectedUser.name} />
                <DetailField label="Email ID" value={selectedUser.email} icon={<Mail size={14} className="text-gray-400"/>} />
                <DetailField label="Phone Number" value={selectedUser.mobile} icon={<Phone size={14} className="text-gray-400"/>} />
                <DetailField label="Date of Birth" value={selectedUser.dateOfBirth || 'N/A'} icon={<Calendar size={14} className="text-gray-400"/>} />
                <DetailField label="Date of Join" value={selectedUser.joinDate} icon={<Calendar size={14} className="text-gray-400"/>} />
                <DetailField label="Address" value={selectedUser.kycData?.address || 'N/A'} icon={<MapPin size={14} className="text-gray-400"/>} />
                
                {selectedUser.userType === 'brand_owner' && (
                  <>
                    <DetailField label="Brand Name" value={selectedUser.brandName || 'N/A'} icon={<Building2 size={14} className="text-gray-400"/>} />
                    <DetailField label="Business Address" value={selectedUser.kycData?.businessAddress || 'N/A'} icon={<MapPin size={14} className="text-gray-400"/>} />
                    <DetailField label="Business Reg No" value={selectedUser.businessRegNo || 'N/A'} />
                    <DetailField label="GST Number" value={selectedUser.gstNo || 'N/A'} />
                  </>
                )}
              </section>

              {/* Section 2: KYC & Bank Details */}
              <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 bg-gray-50 p-4 rounded-lg">
                <div className="col-span-full md:col-span-2 lg:col-span-4 mb-2 flex items-center gap-2">
                  <Shield className="text-green-600" size={18} />
                  <h3 className="text-lg font-semibold text-gray-800">Verification & Banking</h3>
                </div>

                <DetailField label="KYC Status" value={selectedUser.kycVerified ? 'Verified' : 'Pending'}>
                  {selectedUser.kycVerified ? 
                    <span className="px-2 py-0.5 bg-green-100 text-green-800 text-xs rounded-full">Verified</span> : 
                    <span className="px-2 py-0.5 bg-red-100 text-red-800 text-xs rounded-full">Pending</span>
                  }
                </DetailField>
                <DetailField label="PAN Number" value={selectedUser.kycData?.pan || 'N/A'} />
                <DetailField label="Aadhar Number" value={selectedUser.kycData?.aadhaar || 'N/A'} />
                <DetailField label="Bank Status" value={selectedUser.bankAccount ? 'Verified' : 'Not Added'}>
                  {selectedUser.bankAccount ? 
                    <span className="px-2 py-0.5 bg-green-100 text-green-800 text-xs rounded-full">Verified</span> : 
                    <span className="px-2 py-0.5 bg-red-100 text-red-800 text-xs rounded-full">Not Added</span>
                  }
                </DetailField>
                
                {selectedUser.bankAccount ? (
                  <>
                    <DetailField label="Account Number" value={selectedUser.bankAccount.accountNumber} icon={<CreditCard size={14} className="text-gray-400"/>} />
                    <DetailField label="Account Holder" value={selectedUser.bankAccount.accountHolder} />
                    <DetailField label="IFSC Code" value={selectedUser.bankAccount.ifsc} />
                    <DetailField label="Bank Name" value={selectedUser.bankAccount.bankName} />
                  </>
                ) : (
                  <div className="col-span-4 text-center text-sm text-gray-400 py-2">
                    No banking details available
                  </div>
                )}
              </section>

              {/* Section 3: Direct Children Statistics */}
              <section className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4 border border-blue-100 p-4 rounded-lg">
                <div className="col-span-full mb-2 flex items-center gap-2">
                  <Users className="text-blue-600" size={18} />
                  <h3 className="text-lg font-semibold text-gray-800">Direct Children Statistics</h3>
                </div>

                <StatBox label="Left Count" value={selectedUser.leftCount} color="blue" />
                <StatBox label="Right Count" value={selectedUser.rightCount} color="blue" />
                <StatBox label="Total Direct" value={selectedUser.totalCount} color="blue" highlight />
                
                <div className="col-span-full md:col-span-3 lg:col-span-6 h-px bg-gray-200 my-2"></div>

                <CurrencyStatBox label="L Purchase Value" value={selectedUser.leftPurchaseValue} />
                <CurrencyStatBox label="R Purchase Value" value={selectedUser.rightPurchaseValue} />
                <CurrencyStatBox label="Total Purchase" value={selectedUser.totalPurchaseValue} highlight />
                
                <CurrencyStatBox label="L Income" value={selectedUser.leftIncome} />
                <CurrencyStatBox label="R Income" value={selectedUser.rightIncome} />
                <CurrencyStatBox label="Total Income" value={selectedUser.totalIncome} highlight />
              </section>

              {/* Section 4: Indirect Children Statistics (Only for Customers or if requested for BO) */}
              {(selectedUser.userType === 'customer') && (
                <section className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4 border border-purple-100 p-4 rounded-lg">
                  <div className="col-span-full mb-2 flex items-center gap-2">
                    <Package className="text-purple-600" size={18} />
                    <h3 className="text-lg font-semibold text-gray-800">Indirect Team Statistics</h3>
                  </div>

                  <StatBox label="Left Count" value={selectedUser.leftCount} color="purple" />
                  <StatBox label="Right Count" value={selectedUser.rightCount} color="purple" />
                  <StatBox label="Total Indirect" value={selectedUser.totalCount} color="purple" highlight />
                  
                  <div className="col-span-full md:col-span-3 lg:col-span-6 h-px bg-gray-200 my-2"></div>

                  <CurrencyStatBox label="L Purchase Val" value={selectedUser.leftPurchaseValue} />
                  <CurrencyStatBox label="R Purchase Val" value={selectedUser.rightPurchaseValue} />
                  <CurrencyStatBox label="Total Purchase" value={selectedUser.totalPurchaseValue} highlight />
                  
                  <CurrencyStatBox label="L Income" value={selectedUser.leftIncome} />
                  <CurrencyStatBox label="R Income" value={selectedUser.rightIncome} />
                  <CurrencyStatBox label="Total Income" value={selectedUser.totalIncome} highlight />
                </section>
              )}
            </div>

            {/* Modal Footer */}
            <div className="p-4 border-t border-gray-200 bg-gray-50 flex justify-end">
              <button 
                onClick={() => setSelectedUser(null)}
                className="px-6 py-2 bg-white border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-100 font-medium transition"
              >
                Close Details
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Sub-components for cleaner rendering
const DetailField = ({ label, value, icon, children }) => (
  <div className="flex flex-col">
    <span className="text-xs text-gray-500 mb-1 flex items-center gap-1">{label} {icon}</span>
    <span className="text-sm font-medium text-gray-900 truncate">{children || value}</span>
  </div>
);

const StatBox = ({ label, value, color, highlight }) => (
  <div className={`p-3 rounded-lg ${highlight ? 'bg-gray-800 text-white' : `bg-${color}-50 text-${color}-800'} border border-${color}-100`}`}>
    <div className="text-xs opacity-80 mb-1">{label}</div>
    <div className="text-lg font-bold">{value}</div>
  </div>
);

const CurrencyStatBox = ({ label, value, highlight }) => (
  <div className={`p-3 rounded-lg ${highlight ? 'bg-gray-800 text-white' : 'bg-gray-50 text-gray-800 border border-gray-200'}`}>
    <div className="text-xs opacity-80 mb-1 truncate" title={label}>{label}</div>
    <div className="text-sm font-bold">₹{value.toLocaleString('en-IN')}</div>
  </div>
);

export default AdminDashboard;